name: example
description: A theme preview example.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
